apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - nodejs-deployment.yaml
  - python-deployment.yaml
  - go-deployment.yaml
  - traffic-generator.yaml
  - prometheus/prometheus-rbac.yaml
  - prometheus/prometheus-deployment.yaml
  - prometheus/kube-state-metrics.yaml
  - grafana/grafana-deployment.yaml
  - fargate-logging.yaml
